Added Create, Update and Delete for User
SecuritySolutionsSVP/CPM pull request #2
Opened 2021-05-27 08:52 UTC by christian1dk

2021-05-31 11:11 UTC, Yoropiata requested changes

2021-05-31 11:11 UTC, Yoropiata commented on app/Http/Controllers/UserController.php
> +        if (!empty($input['password'])) {
I think this password change should be handled by a specific request to change password that requires entering the current password.

2021-05-31 11:11 UTC, Yoropiata commented on app/Http/Controllers/UserController.php
> +    {
we need a force delete endpoint too for admin

2021-05-31 11:11 UTC, Yoropiata commented on routes/web.php
> +    Route::post('/user/create', [UserController::class, "create"]);
create is inferred by the post command. I recommend using `/user`

2021-05-31 11:11 UTC, Yoropiata commented on routes/web.php
> +    Route::put('/user/update', [UserController::class, "update"]);
update is inferred by put, however user id should be attached, I recommend `/user/{id}`

2021-05-31 11:11 UTC, Yoropiata commented on routes/web.php
> +    Route::delete('/user/delete',[UserController::class, "delete"]);
delete is inferred by delete request type, however user id should be attached, I recommend `/user/{id}`

For the force delete endpoint, I recommend `/user/{id}/force` request must be of type `delete`

2021-05-31 11:37 UTC, christian1dk commented on app/Http/Controllers/UserController.php
> +    {
We need a soft delete endpoint, but we need that option in the database

2021-05-31 11:39 UTC, christian1dk commented on routes/web.php
> +    Route::put('/user/update', [UserController::class, "update"]);
Would we send that in the url?
We use request now.

2021-05-31 11:39 UTC, christian1dk commented on routes/web.php
> +    Route::delete('/user/delete',[UserController::class, "delete"]);
Would we send that in the url?
We use request now.

2021-05-31 12:04 UTC, christian1dk commented on routes/web.php
> +    Route::put('/user/update', [UserController::class, "update"]);
what is the difference if we send it as /user/{id} or /user?{id}

2021-05-31 12:04 UTC, christian1dk commented on routes/web.php
> +    Route::delete('/user/delete',[UserController::class, "delete"]);
what is the difference if we send it as /user/{id} or /user?{id}

2021-06-02 06:58 UTC, numtjok approved these changes

2021-06-02 10:39 UTC, Yoropiata approved these changes

2021-06-02 10:40 UTC, merged