Added Create, Update and Delete for Group
SecuritySolutionsSVP/CPM pull request #3
Opened 2021-05-27 11:53 UTC by christian1dk

2021-05-31 11:12 UTC, Yoropiata requested changes

2021-05-31 11:12 UTC, Yoropiata commented on app/Http/Controllers/GroupController.php
> +            'name' => 'required',
Jeg mener laravel har indbygget validation til unique usernames.

Tror syntaks er noget ala: 
`'name' => 'required:groups,name'. Så slipper du for manuelt at skulle tjekke efter uniqueness / håndtere de fejl der medfølger.

2021-05-31 11:12 UTC, Yoropiata commented on app/Http/Controllers/GroupController.php
> +            'name' => 'required',
Det skal selvfølgeligt også tjekkes ved update requesten

2021-05-31 11:12 UTC, Yoropiata commented on app/Http/Controllers/GroupController.php
> +        $input = $request->all();
Jeg ville bruge `$request->only('name', 'someOtherField')`

2021-06-02 06:57 UTC, numtjok approved these changes

2021-06-02 11:12 UTC, Yoropiata approved these changes

2021-06-02 11:12 UTC, merged