Added Create, Read, Update and Delete for Role
SecuritySolutionsSVP/CPM pull request #4
Opened 2021-05-27 12:57 UTC by christian1dk

2021-05-31 11:12 UTC, Yoropiata requested changes

2021-05-31 11:12 UTC, Yoropiata commented on app/Http/Controllers/RoleController.php
> +        $input = $request->all();
Benyt dig af `$request->only('name', 'priviledge_level');`

2021-06-02 06:56 UTC, numtjok approved these changes

2021-06-02 11:11 UTC, Yoropiata commented
Merge conflict

2021-06-02 11:20 UTC, Yoropiata approved these changes

2021-06-02 11:20 UTC, merged